---
title: "Code"
output: html_document
---
```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 12, fig.height = 8, warning = FALSE, message = FALSE)

#check for needed packages, install if needed, require if not
ndpkg <- function(p){
 ifelse(is.element(p,installed.packages()[,1]),require(p,character.only = T), install.packages(p, dep = T))
}
sapply(c("ggplot2", "reshape", "gridExtra", "mgcv", "dplyr"), ndpkg)
```

```{r Data Wrangling}
#Load needed data: md0, md00, lon, lat, year, month, prec, tavg
load("~/Desktop/Project 1/Data/General/lat.jdata.rda")
load("~/Desktop/Project 1/Data/General/lon.jdata.rda")
load("~/Desktop/Project 1/Data/General/md0.jdata.rda")
load("~/Desktop/Project 1/Data/General/md00.jdata.rda")
load("~/Desktop/Project 1/Data/General/year.jdata.rda")
load("~/Desktop/Project 1/Data/General/month.jdata.rda")
load("~/Desktop/Project 1/Data/General/prec.jdata.rda")
load("~/Desktop/Project 1/Data/General/tavg.jdata.rda")

#Create a gridded annual md0 index
md00y <- md00[month==7] #Only need one month of the annual md0
md00yg <- by(md00y,list(lon[month==7],lat[month==7],year[month==7]),median)
md00ygs <- aperm(apply(md00yg,1:2,scale), c(2,3,1)) #scaling and reordering dimensions (z-scores)
md0s <- aperm(apply(md0, 1:2, scale), c(2,3,1))
tavgs <- aperm(apply(tavg, 1:2, scale), c(2,3,1))
precs <- aperm(apply(prec, 1:2, scale), c(2,3,1))

#data frame of all variables
all_var <- as.data.frame(cbind(year, month, lat, lon, md00, md00ygs, md0, md0s, prec, precs, tavg, tavgs))
 
```

```{r Drought Criteria}
#2 year drought, z-score thresholds == 0, 1, 2 
mi20 <- ifelse(((md00ygs[,,1:96]>=0)+(md00ygs[,,2:97]>=0))==2,1,NA)
mi21 <- ifelse(((md00ygs[,,1:96]>=1)+(md00ygs[,,2:97]>=1))==2,1,NA)
mi22 <- ifelse(((md00ygs[,,1:96]>=2)+(md00ygs[,,2:97]>=2))==2,1,NA)
         
#3 year drought, z-score threshold == 0, 1, 2
mi30 <- ifelse(((md00ygs[,,1:95]>=0)+(md00ygs[,,2:96]>=0)+(md00ygs[,,3:97]>=0))==3,1,NA)  
mi31 <- ifelse(((md00ygs[,,1:95]>=1)+(md00ygs[,,2:96]>=1)+(md00ygs[,,3:97]>=1))==3,1,NA)  
mi32 <- ifelse(((md00ygs[,,1:95]>=2)+(md00ygs[,,2:96]>=2)+(md00ygs[,,3:97]>=2))==3,1,NA)  
         
#5 year drought, z-score threshold == 0, 1, 2
mi50 <- ifelse(((md00ygs[,,1:93]>=0)+(md00ygs[,,2:94]>=0)+(md00ygs[,,3:95]>=0)+(md00ygs[,,4:96]>=0)+(md00ygs[,,5:97]>=0))==5,1,NA)
mi51 <- ifelse(((md00ygs[,,1:93]>=1)+(md00ygs[,,2:94]>=1)+(md00ygs[,,3:95]>=1)+(md00ygs[,,4:96]>=1)+(md00ygs[,,5:97]>=1))==5,1,NA)         
mi52 <- ifelse(((md00ygs[,,1:93]>=2)+(md00ygs[,,2:94]>=2)+(md00ygs[,,3:95]>=2)+(md00ygs[,,4:96]>=2)+(md00ygs[,,5:97]>=2))==5,1,NA)         
         

#compare criteria visually
rnk_per <- data.frame(Year = 1918:2014, percent_20 = NA, percent_21 = NA, percent_22 = NA, percent_30 = NA, percent_31 = NA, percent_32 = NA, percent_50 = NA, percent_51 = NA, percent_52 = NA)

#total core cells/ total land cells
for (i in 1:96){
	rnk_per[i+1,2]<- 100 * (sum(!is.na(mi20[ , , i])) / sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+1,3]<- 100 * (sum(!is.na(ifelse(mi21[ , ,i] >= 1, 1, NA))) / sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+1,4]<- 100 * (sum(!is.na(ifelse(mi22[ , ,i] >= 2, 1, NA))) / sum(!is.na(md00ygs[ , , i])))
}

for (i in 1:95){
	rnk_per[i+2,5]<- 100 * (sum(!is.na(mi30[ , , i]))/
	sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+2,6]<- 100 * (sum(!is.na(ifelse(mi31[ , ,i] >= 1, 1, NA)))/sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+2,7]<- 100 * (sum(!is.na(ifelse(mi32[ , ,i] >= 2, 1, NA)))/sum(!is.na(md00ygs[ , , i])))
}

for (i in 1:93){
	rnk_per[i+4,8]<- 100 * (sum(!is.na(mi50[ , , i]))/
	sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+4,9]<- 100 * (sum(!is.na(ifelse(mi51[ , ,i] >= 1, 1, NA)))/sum(!is.na(md00ygs[ , , i])))
	rnk_per[i+4,10]<- 100 * (sum(!is.na(ifelse(mi52[ , ,i] >= 2, 1, NA)))/sum(!is.na(md00ygs[ , , i])))
}

rnk_per_m <- melt(rnk_per[,2:10])
colnames(rnk_per_m) <- c("Threshold", "Percentage")
rnk_per_m$Year <- rep(1918:2014, 9)
rnk_per_m$Window <- substr(rnk_per_m$Threshold, 1, 9)

rnk_graph <- ggplot(data = rnk_per_m, aes(x = Year, y = Percentage, color = Threshold)) + geom_line() + facet_grid(Window~., scale = "free") + theme_minimal() + ggtitle("Drought as Percentage of Study Area") 

#Intensity
mi31_sum<-(md00ygs[,,1:95]>=1)+(md00ygs[,,2:96]>=1)+(md00ygs[,,3:97]>=1)
for (i in 1:95){
mi31_sum[,,i]<-ifelse(mi31_sum[,,i]==3,((md00ygs[,,i])+(md00ygs[,,i+1])+(md00ygs[,,i+2])), NA)
} #replace the 3 year drought areas with their summed anomalies, then sum all the anomalies for the drought

rnk_int <- data.frame(Year = 1918:2014, Intensity = NA)
for (i in 1:95){
	rnk_int[i+2,2]<- sum(mi31_sum[ , , i], na.rm = T)
}

int_lab<- as.data.frame(cbind(rnk_int$Year[which(rnk_int$Intensity >= 2000)], rnk_int$Intensity[which(rnk_int$Intensity >= 2000)]))

ggplot(data = rnk_int, aes(x = Year, y = Intensity)) + geom_line() + labs(title = "Sum of SD in drought areas, years -3 to 0", x = "Year", y = "Sum S.D.") + geom_label(data = int_lab, aes(x = V1, y = V2, label = V1), position = "dodge") +theme_minimal()

```

```{r Overall plots}
mdfrq<-apply(mi31,c(1,2),sum,na.rm=T)
mdfrq[mdfrq == 0] <- NA
All = melt(mdfrq)
frac_drght <- sum(!is.na(mdfrq))/26026

mdfrq1_94<-apply(mi31[,,1:94],c(1,2),sum,na.rm=T)
mdfrq1_94[mdfrq1_94 == 0] <- NA
All_less = melt(mdfrq1_94)

mdfrq1_48<-apply(mi31[,,1:48],c(1,2),sum,na.rm=T)
mdfrq1_48[mdfrq1_48 == 0] <- NA
Half1 = melt(mdfrq1_48)

mdfrq48_95<-apply(mi31[,,48:95],c(1,2),sum,na.rm=T)
mdfrq48_95[mdfrq48_95 == 0] <- NA
Half2 = melt(mdfrq48_95)

mdfrq48_94<-apply(mi31[,,48:94],c(1,2),sum,na.rm=T)
mdfrq48_94[mdfrq48_94 == 0] <- NA
Half_less = melt(mdfrq48_94)

mdfrq95<-apply(mi31[,,95],c(1,2),sum,na.rm=T)
mdfrq95[mdfrq95 == 0] <- NA
Last1 = melt(mdfrq95)


frq2 <- melt(data.frame(ac_All = All[,3], ad_Half1 = Half1[,3], ae_Half2 = Half2[,3], bc_All_less = All_less[,3], bd_Half_less = Half_less[,3], be_Last = Last1[,3]))

frq2$Lat <- rep(All[,1], 6)
frq2$Lon <- rep(All[,2], 6)
frq2$xx <- substr(frq2$variable, 2,2)
frq2$yy <- substr(frq2$variable, 1,1)

cnt_graph <- ggplot(frq2, aes(x = Lat, y = Lon, z = value, fill = value)) + geom_tile() + coord_equal() +  scale_fill_distiller(palette="Spectral", na.value="white") + borders("state", xlim = c(-124.6875, -102.0625), ylim = c(31.1875, 48.9375)) + facet_grid(xx~yy, scales = "free") + theme_minimal()

```

```{r year plots}
#We have identified 2014, 1931, 1936, 1956, 2002, and 1961 as the years that deserve a closer look.  The plot from this code will be a 5 x 6 plot, with the year in question as the rightmost plot.
